import Head from 'next/head'
import type { Metadata } from 'next'
 
// These styles apply to every route in the application
import './globals.css'
 
export const metadata: Metadata = {
  title: 'The Wall Art',
  description: 'Generated by Fazilat Jahan',
}
 
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="favicon.ico" sizes="any" />
      </Head>
      <body>{children}</body>
    </html>
  )
}